const lists = {
  "gravity":[{
    img:require("../img/shiko.jpg"),
    title:"ようこそ！！",
    text:"三重県立四日市高校です。今から私たちの発表を始めます",
    color:"#35af55"
  },{
    img:null,
    title:"研究目的",
    text:"私たちの研究の目的は重力加速度を様々な方法で測定することです。",
    color:"#a5ad34"
   },{
    img:require("../img/fall.png"),
    title:"重力とは",
    text:"重力とは、地球が物体を引っ張る万有引力と地球の自転による遠心力の合力です。 ",
    color:"#2196f3"
  },{
    title:"重力加速度",
    text:"重力加速度とは、重力によって生じる加速度のことです。",
    color:"#af7e35"
  },{
    img:require("../img/g2yt2.png"),
    title:"How to calculate",
    text:"It is calculated by formula above.(t: time, y: height)",
    color:"#4caf50",
  },{
    img:require("../img/five.png"),
    title:"測定方法",
    text:"私たちは５種類の実験から重力加速度を求めました。 [Next]ボタンをクリックして、実験の詳細を見に行きましょう!",
    color:"#ef6c00",
    buttons:[{
      label:"Next"
    }]
  }],
  "ffOpt":[{
    title:"光センサーを使った自由落下の実験",
    text:"この実験では、私たちは鉄球の自由落下にかかる時間を正確に測れる装置を自作しました。",
    color:"#7cb342",
    
  },{
    img:require("../img/laser.png"),
    title:"実験原理1",
    text:"この実験では鉄球の落下を検出する光センサーを２つ使いました",
    color:"#7cb342",
  },{
    img:require("../img/laser.png"),
    title:"実験原理2",
    text:"２つのセンサー間の時間差を求めることで重力加速度の値を求めることができます。",
    color:"#7cb342",
  },{
    img:require("../img/g2yt2.png"),
    title:"公式",
    text:"この実験では、重力加速度の値を求めるためにこの式を使いました。",
    color:"#7cb342",
    buttons:[{
      label:"トップに戻る"
    }]
   }],
  "ffSW":[{
    title:"ストップウォッチとスイッチを使った自由落下の実験",
    text:"この実験では、私たちは鉄球の自由落下にかかる時間を正確に測れる装置を自作しました。",
    color:"#62b8e2",
  },{
    img:require("../img/ffSW.png"),
    title:"実験器具",
    text:"この実験ではストップウォッチ、電磁石、プッシュスイッチを使いました。これらの器具を使うことで 自由落下の開始から終了までの時間を測ることができます。",
    color:"#8ac8e6",
  },{
    img:require("../img/atwood.png"),
    title:"実験装置",
    text:"電磁石の電源を切ると、鉄球が落ち、それと同時に時間の測定が開始され、 鉄球がプッシュスイッチに衝突すると時間の測定を終了する装置を組み立てました。",
    color:"#8ac8e6",
  },{
    img:require("../img/g2yt2.png"),
    title:"実験原理",
    text:"自由落下にかかった時間と落ちた高さを測ることで重力加速度の値を求めることができます。",
    color:"#8ac8e6",
  },{
    img:require("../img/g2yt2.png"),
    title:"公式",
    text:"今回の実験では、この公式を使いました。",
    color:"#8ac8e6",
    buttons:[{
      label:"トップへ戻る"
    }]
   }],
  "atwood":[{
    img:require("../img/atwood.png"),
    title:"アトウッドの器械",
    text:"アトウッドの器械は１８世紀終わりに開発された装置です。この装置は物体の加速度を測定するのに使われます。",
    color:"#62b8e2",
  },{
    img:require("../img/atwood.png"),
    title:"実験手法",
    text:"この実験では２つの質量の異なる物体を糸でつなぎ、滑車にかけます。",
    color:"#62b8e5",
  },{
    img:require("../img/atwood.png"),
    title:"実験原理",
    text:"物体をおさえていた手を放すと、物体は動き出します。高さと落下時間を測ることで重力加速度を求めることができます。",
    color:"#62b8e5",
  },{
    img:require("../img/atwood_formula.png"),
    title:"公式",
    text:"今回の実験ではこの公式を使いました。",
    color:"#62b8e5",
   },{
    img:require("../img/grav.png"),
    title:"さあ",
    text:"実際に重力加速度の値を測定してみましょう！ということで、机上の実験装置に注目してください",
    color:"#62b8e5",
     buttons:[{
      label:"トップに戻る"
    }]
  }],
  "aldebaran":[{
    img:require("../img/aldebaran_pic_en.png"),
    title:"アルデバラン食",
    text:"この実験では、重力加速度を求めるためにアルデバラン食を使いました。",
    color:"#78909c",
  },{
    img:require("../img/aldebaran_en.gif"),
    title:"ところで、アルデバラン食とはなんでしょうか？ ",
    text:"この画像を見てください。アルデバラン食は十数年に一度の天体ショーです。 この機会を生かして、私たちはアルデバラン食を観察しました。",
    color:"#78909c",
  },{
    title:"実験原理",
    text:"地球の半径と、月と地球の距離はよく知られた値です。そのため、月の公転の角速度を測ることで重力加速度を求めることができます。",
    color:"#78909c",
  },{
    img:require("../img/aldebaran_formula.png"), //png?
    title:"公式",
    text:"この実験では、この公式を使いました。",
    color:"#78909c",
    buttons:[{
      label:"トップへ戻る"
    }]
  }],
  "spring":[{
    img:require("../img/spring_en.png"),
    title:"鉛直バネ振り子",
    text:"鉛直バネ振り子はバネと物体とをつないだ実験装置です。",
    color:"#f06292",
  },{
    img:require("../img/pendulum.png"),
    title:"実験原理",
    text:"物体を下に引っ張って放すと、物体は垂直に振動します。その周期を測ることから重力加速度を求めることができます。",
    color:"#f06292",
  },{
    img:require("../img/aokiware.png"),
    title:"解析方法",
    text:"この実験では新たにソフトウェアを作り、動画を解析しました。",
    color:"#f06292",
  },{
    img:require("../img/grav.png"),
    title:"公式",
    text:"この実験では、この公式を使いました。",
    color:"#f06292",
    buttons:[{
      label:"トップへ戻る"
    }]
   }]
}
const util = require("../util")
module.exports=require("./tutorial.html")({
  data(){
    return {
      index:0,
      items:[]
    }
  },
  props:["itemName","goNext"],
  methods:{
    buttonClicked(btn){
      if(btn.push){
        this.$store.commit("push",btn.push)
      }else if(btn.url){
        util.openUrl(btn.url)
      }else{
        if(this.index>this.items.length-2){
          this.skip()
        }else{
          this.index++
        }
      }
    },
    skip(){
      if(this.goNext){
        this.$store.commit("push",this.goNext)
      }else{
        this.$store.commit("pop")
        
      }
    }
    
  },
  created(){
    this.items=lists[this.itemName||"gravity"]
  }
})
